# Generated by Django 6.0.6 on 2026-06-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название станции')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_number', models.IntegerField(verbose_name='Номер маршрута')),
                ('numbers_wagons', models.IntegerField(verbose_name='Количество вагонов')),
                ('departure_point', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('arrival_point', models.CharField(max_length=100, verbose_name='Пункт конечного прибытия')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('rfid_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_uid', models.CharField(max_length=50, unique=True, verbose_name='Идентификатор метки')),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station_control.train', verbose_name='Поезд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_control.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='PassEvent',
            fields=[
                ('pass_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Время прохождения')),
                ('status', models.CharField(choices=[('OK', 'Штатное прибытие'), ('ERROR', 'Ошибка идентификации'), ('DUPLICATE', 'Дубликат')], default='OK', max_length=20, verbose_name='Статус события')),
                ('rfid_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_control.rfidtag', verbose_name='RFID-метка')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_control.station', verbose_name='Станция')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_control.train', verbose_name='Поезд')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_control.user', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='station',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_control.user', verbose_name='Пользователь'),
        ),
    ]
