# Generated by Django 6.0.6 on 2026-06-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_control.user', verbose_name='Пользователь'),
        ),
    ]
